adição da tradução do Rules\Password
lucascudo/laravel-pt-BR-localization pull request #42
Opened 2021-08-20 13:18 UTC by nicolauns

2021-09-01 01:37 UTC, danilomartins90 commented
Estou usando a ultima versão do pacote de tradução, mas não está funcionando a tradução das Rules Password, ele da as mensagens em EN. Como faço para ativar a tradução para essas mensagens?

2021-09-01 10:36 UTC, ricocrivelli approved these changes

2021-09-01 10:38 UTC, ricocrivelli commented
> 
> 
> Estou usando a ultima versão do pacote de tradução, mas não está funcionando a tradução das Rules Password, ele da as mensagens em EN. Como faço para ativar a tradução para essas mensagens?

Essa pull ainda não foi unificado ao código principal. Você pode clonar o branch https://github.com/nicolauns/laravel-pt-BR-localization ou verificar as modificações e inserir por conta própria https://github.com/lucascudo/laravel-pt-BR-localization/pull/42/files

2021-09-01 23:44 UTC, ricocrivelli requested changes
Faltou uma linha:

`
"The given :attribute has appeared in a data leak. Please choose a different :attribute.": "A senha que você inseriu em :attribute está em um vazamento de dados. Por favor escolha uma senha diferente."
`

2021-09-02 22:12 UTC, nicolauns commented
pronto adicionei a mensagem de data leak de senha

2021-09-02 22:15 UTC, ricocrivelli commented
> 
> 
> pronto adicionei a mensagem de data leak de senha

Boa!!

2021-09-07 08:14 UTC, merged